docker: Install argp.h
The 5.10 build fails with:

  CC [U]  kernel/bpf/preload/iterators/iterators.o
kernel/bpf/preload/iterators/iterators.c:3:10: fatal error: argp.h: No such file or directory
    3 | #include <argp.h>
      |          ^~~~~~~~
compilation terminated.

Fix by installing the required header.